In [169]:

a=1
b=2
c=a + b
print(c)


3


In [170]:

x=[0,1,2,3,4,5]
print(x[:2])
print(x[2:])



[0, 1]
[2, 3, 4, 5]


In [171]:
x=[1,2,3]
y=x
y[-1]=4
print (x)

[1, 2, 4]


In [172]:
for i in range(5):
    if i >=2 : break
    print(i)

0
1


In [173]:
for i in range(5):
    if i ==2 : continue
    print(i)

0
1
3
4


In [174]:
x=3
if x>3:
    print ("too big")
elif x < 1:
    print ("too small")
else:
    print ("just right")    

just right


In [175]:
a=1
def f(x):
    return x+a
def g(x,a=1):
    return x+a
print (f(1))
print (g(1))
a=2
print (f(1))
print (g(1))

2
2
3
2


In [176]:
import numpy as np
x = np.array([1,2,3])
y=x
x+=1
print (y)
x[:]=x+1
print (y)
x=x+1
print (y)


[2 3 4]
[3 4 5]
[3 4 5]


In [177]:
class SquareClass:
    def __init__(self,length,width):
        self.length=length
        self.width=width
    def size(self):
        return self.length * self.width
square=SquareClass (2,2)
print(square.size())


4
